language: node_js
dist: trusty

node_js: '10'
#  - '8'
#  - '9'
#  - '10'
#  - '11'

matrix:
  include:
    - node_js: '8'
      env: RUN=jest
    - node_js: '9'
      env: RUN=jest
    - node_js: '10'
      env: RUN=jest
    - node_js: '11'
      env: RUN=jest
    - node_js: '10'
      env: RUN=karma

# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
branches:
  except:
    - master

cache: yarn

env:
  global:
    - TRAVIS=true

#before_script:
#  - yarn add "coveralls"@"^3.0.2" "jest"@"^23.6.0"
#  - sudo apt-get install tree
#  - tree test

script:
  - /bin/bash travis.sh

#after_success:
#  - cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js



