name: Jest Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  tests:
    timeout-minutes: 3
    runs-on: ubuntu-20.04 # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18] # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: make yarn
        run: make yarn
      - name: tests
        run: |
          /bin/bash test.sh
